version: "3.9"
services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: smartrelief-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-smartrelief_dev}
      POSTGRES_USER: ${POSTGRES_USER:-smartrelief}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - smartrelief-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-smartrelief}"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: smartrelief-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smartrelief-network
    command: ["sh", "-c", "redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
      target: development
    container_name: smartrelief-backend
    environment:
      NODE_ENV: development
      SEED_ON_START: "true"
      DATABASE_URL: "postgresql://smartrelief:password@postgres:5432/smartrelief_dev"
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-0123456789abcdef0123456789abcdef01234567}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      AI_BASE_URL: ${AI_BASE_URL:-http://ai-service:8000/api/v1}
      SOCKET_AUTH_REQUIRED: ${SOCKET_AUTH_REQUIRED:-false}
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      # Mount only source and schema for live reload without clobbering node_modules
      - ./packages/backend/src:/app/src
      - ./packages/backend/prisma:/app/prisma
      - ./packages/backend/package.json:/app/package.json:ro
      - ./packages/backend/tsconfig.json:/app/tsconfig.json:ro
      - ./packages/backend/tsconfig.build.json:/app/tsconfig.build.json:ro
      - ./packages/backend/scripts:/app/scripts
      - ./packages/backend/.env:/app/.env:ro
      - ./packages/shared:/shared
    networks:
      - smartrelief-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  ai-service:
    build:
      context: ./packages/ai-service
      dockerfile: Dockerfile
      target: development
    container_name: smartrelief-ai
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-smartrelief}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-smartrelief_dev}
      REDIS_URL: redis://redis:6379
      BACKEND_API_URL: http://backend:3000
    ports:
      - "8000:8000"
    volumes:
      - ./packages/ai-service:/app
      - ./packages/ai-service/ml_models:/app/ml_models
      - ai_models_cache:/app/.cache
    networks:
      - smartrelief-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: smartrelief-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    networks:
      - smartrelief-network
    depends_on:
      - backend
      - ai-service
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: smartrelief-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - smartrelief-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: smartrelief-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./infrastructure/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: false
    networks:
      - smartrelief-network
    depends_on:
      - prometheus
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: smartrelief-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - smartrelief-network
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: smartrelief-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - smartrelief-network
    depends_on:
      - elasticsearch
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: smartrelief-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - smartrelief-network
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: smartrelief-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    command: server /data --console-address ":9001"
    networks:
      - smartrelief-network
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: smartrelief-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - smartrelief-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: smartrelief-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      # String values in PGADMIN_CONFIG_* must be valid Python literals; wrap banner in quotes
      PGADMIN_CONFIG_LOGIN_BANNER: "'SmartRelief Local pgAdmin'"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - smartrelief-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost/misc/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: smartrelief-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - smartrelief-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8081 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  smartrelief-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  elasticsearch_data:
    driver: local
  minio_data:
    driver: local
  ai_models_cache:
    driver: local
  pgadmin_data:
    driver: local
