global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'ai-service'
    static_configs:
      - targets: ['ai-service:8000']
