apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: smartrelief
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - smartrelief.local
      secretName: smartrelief-local-tls
  rules:
    - host: smartrelief.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /socket.io
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /openapi
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
