apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smartrelief
resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - ai-service.yaml
  - ingress-backend.yaml
  - ingress-ai.yaml
