apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: smartrelief
stringData:
  POSTGRES_DB: smartrelief_dev
  POSTGRES_USER: smartrelief
  POSTGRES_PASSWORD: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: smartrelief
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:15-3.3
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init-sql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: smartrelief
# You can add init SQL files by inlining here; empty for now
# data:
#   01-init.sql: |
#     -- optional
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: smartrelief
spec:
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
